export default {
  HOME: 'Home',
  HOMESTACK: '- Home -',
  PROFILE: 'Profile',
  PROFILESTACK: '- Profile -',
  EXPLORE: 'Explore',
  EXPLORESTACK: '- Explore -',
  TABS: 'Tabs',
  PRODUCT_DETAILS: 'Product Details',
  SEARCH: 'Search',
  EDIT_PROFILE: 'Edit Profile',
  LOGIN: 'Login',
  MAP: 'Map',
  CAMERA: 'Camera',
};
